
name: Minikube Hello API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Definir versão da imagem
        run: |
          $VERSION = "v${{ github.run_number }}-${{ github.sha }}"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Build imagem Docker local
        run: |
          minikube docker-env --shell powershell | Invoke-Expression
          docker build -t hello:${{ env.VERSION }} .

      - name: Atualizar imagem no deployment.yaml
        run: |
          (Get-Content deployment.yaml) -replace 'image: hello:latest', "image: hello:${{ env.VERSION }}" | Set-Content deployment.yaml

      - name: Aplicar Deployment e Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Esperar pods ficarem prontos
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Testar serviço
        run: |
          $url = minikube service hello-service --url
          curl $url
