name: Teste Runner Self-Hosted

on:
  workflow_dispatch:   # permite rodar manualmente pelo botão "Run workflow".

jobs:
  test:
    runs-on: self-hosted   # usa o runner que você registrou
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Step de validação
        run: echo "funcionou!"
