
name: Run Hello in ubuntu/python Container

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/python:3.11
    steps:
      - name: Install tail
        run: apt-get update && apt-get install -y coreutils

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello script
        run: python hello.py
