
name: Run Hello in ubuntu/python Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/python:3.12-24.04  # Use a tag espec√≠fica para evitar surpresas
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Python version
        run: python --version

      - name: Run Hello script
        run: python hello.py
