name: Minikube Hello API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted   # seu runner com Minikube instalado
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagem Docker local
        run: |
          eval $(minikube docker-env)
          docker build -t hello:latest .

      - name: Aplicar Deployment e Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Esperar pods ficarem prontos
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Testar serviço
        run: |
          minikube service hello-service --url
          curl $(minikube service hello-service --url)
