
name: Minikube Hello API

on:
  push:
    branches: [ "main" ]

jobs:
  version:
    runs-on: self-hosted
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Definir versão da imagem
        id: set-version
        run: |
         VERSION="v${{ github.run_number }}-${{ github.sha }}"
         echo "VERSION=$VERSION" >> $GITHUB_ENV


  build:
    runs-on: self-hosted
    needs: version
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker no Minikube
        run: |
          minikube docker-env --shell powershell | Invoke-Expression

      - name: Build imagem Docker local
        run: |
          docker build -t hello:${{ needs.version.outputs.VERSION }} .

      - name: Atualizar imagem no deployment.yaml
        run: |
          (Get-Content deployment.yaml) -replace 'image: hello:latest', "image: usuario/hello:${{ needs.version.outputs.VERSION }}" | Set-Content deployment.yaml

  push:
    runs-on: self-hosted
    needs: [version, build]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag e Push para Docker Hub
        run: |
          IMAGE_NAME="thico/hello"
          VERSION="${{ needs.version.outputs.VERSION }}"
          docker tag hello:$VERSION $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION

  deploy:
    runs-on: self-hosted
    needs: [version, build, push]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Aplicar Deployment e Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Esperar pods ficarem prontos
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Testar serviço
        run: |
          minikube service hello-service --url
          curl $(minikube service hello-service --url)
