
name: Minikube Hello API

on:
  push:
    branches: [ "main" ]

jobs:
  version:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Definir versão da imagem
        run: |
          $VERSION = "v${{ github.run_number }}-${{ github.sha }}"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV


  build-and-push:
    runs-on: self-hosted
    needs: version
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagem Docker
        run: |
          $IMAGE_NAME = "thico/hello"
          docker build -t ${IMAGE_NAME}:${{ env.VERSION }} .
          docker tag ${IMAGE_NAME}:${{ env.VERSION }} ${IMAGE_NAME}:latest

      - name: Push para Docker Hub
        run: |
          $IMAGE_NAME = "thico/hello"
          docker push ${IMAGE_NAME}:${{ env.VERSION }}
          docker push ${IMAGE_NAME}:latest

      - name: Atualizar imagem no deployment.yaml
        run: |
          (Get-Content deployment.yaml) -replace 'image: hello:latest', "image: thico/hello:${{ env.VERSION }}" | Set-Content deployment.yaml

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Aplicar Deployment e Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Esperar pods ficarem prontos
        run: |
          kubectl rollout status deployment/hello-deployment

      - name: Testar serviço
        run: |
          minikube service hello-service --url
          curl $(minikube service hello-service --url)
